baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Gan's Devlog"

theme = "simpledevlog"

#googleAnalytics = "UA-123-45"

[params]
    description = "Gan's devlog"
    author = "Chungkwon Ryu"
    authorImage = "/images/author-cat.jpg"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/ryuch91"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
    name = "About"
    url = "/about"

[[menu.footer]]
    name = "Privacy"
    url = "/privacy"
